simTime: 1000000
numNodes: 200000
enterRate: 750
exitRate: 750
gridHeight: 10000
gridWidth: 10000
chaffGenRate: 2500
txGenRate: 7500
circuitWidth: 4
circuitDepth: 6
retryLimit: 100
buffSize: 5
mixDelay: 5
pktSize: 1024
seed: 256
outfileprefix: "config_10e7"
path: "."
genMatrices: false