simTime: 2500
numNodes: 150000
enterRate: 750
exitRate: 750
gridHeight: 100
gridWidth: 100
chaffGenRate: 5000
txGenRate: 7500
circuitWidth: 2
circuitDepth: 6
retryLimit: 7500
buffSize: 10
mixDelay: 50
pktSize: 1024
seed: 256
outfileprefix: "config_10e5"
path: "."
genMatrices: false
initialAddressSize: 250
validNodeTransmitReq: 50
addressBookSize: 1000
