simTime: 10000
numNodes: 1000
enterRate: 750
exitRate: 750
gridHeight: 10000
gridWidth: 10000
chaffGenRate: 5000
txGenRate: 7500
circuitWidth: 4
circuitDepth: 6
retryLimit: 1000
buffSize: 10
mixDelay: 50
pktSize: 1024
seed: 256
outfileprefix: "config_10e3"
path: "."
genMatrices: false
initialAddressSize: 250
validNodeTransmitReq: 50
addressBookSize: 1000

# java -classpath ../jyaml-1.3.jar:. -Xmx6g Boomerang ../config/config_10e3.yaml