simTime: 1000000
numNodes: 10000000
enterRate: 2
exitRate: 100
gridHeight: 100
gridWidth: 100
chaffGenRate: 4
txGenRate: 5
circuitWidth: 2
circuitDepth: 2
retryLimit: 5
buffSize: 1
mixDelay: 1
pktSize: 1024
seed: 256
outfileprefix: "config_10e7"
path: "."
genMatrices: false