simTime: 30000
numNodes: 150
enterRate: 750
exitRate: 750
gridHeight: 10000
gridWidth: 10000
chaffGenRate: 7500
txGenRate: 15000
circuitWidth: 1
circuitDepth: 8
retryLimit: 7500
buffSize: 10
mixDelay: 50
pktSize: 1024
seed: 256
outfileprefix: "sim10"
path: "."
genMatrices: false
initialAddressSize: 250
validNodeTransmitReq: 50
addressBookSize: 1000

# java -classpath ../jyaml-1.3.jar:. -Xmx6g Boomerang ../config/config_10e3.yaml