simTime: 100
numNodes: 5
enterRate: 2
exitRate: 2
gridHeight: 100
gridWidth: 100
chaffGenRate: 4
txGenRate: 4
circuitWidth: 2
circuitDepth: 2
retryLimit: 1
buffSize: 1
mixDelay: 1
pktSize: 1024
seed: 256
