simTime: 1000
numNodes: 1000
enterRate: 750
exitRate: 750
gridHeight: 100
gridWidth: 100
chaffGenRate: 2500
txGenRate: 7500
circuitWidth: 4
circuitDepth: 5
retryLimit: 1
buffSize: 5
mixDelay: 5
pktSize: 1024
seed: 256
outfileprefix: "config_10e3"
path: "."
genMatrices: false