simTime: 200000
numNodes: 2000
enterRate: 550
exitRate: 500
gridHeight: 10000
gridWidth: 10000
chaffGenRate: 2000
txGenRate: 5000
circuitWidth: 12
circuitDepth: 4
retryLimit: 7500
buffSize: 50
mixDelay: 50
pktSize: 1024
seed: 256
outfileprefix: "lsdC4"
path: "."
genMatrices: false
initialAddressSize: 250
validNodeTransmitReq: 50
addressBookSize: 1000
keepInMemory: false