simTime: 200000
numNodes: 200
enterRate: 5000
exitRate: 5000
gridHeight: 10000
gridWidth: 10000
chaffGenRate: 200
txGenRate: 1000
circuitWidth: 4
circuitDepth: 8
retryLimit: 7500
buffSize: 50
mixDelay: 50
pktSize: 1024
seed: 256
outfileprefix: "sbs48"
path: "."
genMatrices: false
initialAddressSize: 250
validNodeTransmitReq: 50
addressBookSize: 1000
keepInMemory: false