simTime: 200000
numNodes: 200
enterRate: 500
exitRate: 550
gridHeight: 10000
gridWidth: 10000
chaffGenRate: 2000
txGenRate: 5000
circuitWidth: 1
circuitDepth: 4
retryLimit: 7500
buffSize: 50
mixDelay: 50
pktSize: 1024
seed: 256
outfileprefix: "ssg14"
path: "."
genMatrices: false
initialAddressSize: 250
validNodeTransmitReq: 50
addressBookSize: 1000
keepInMemory: false