simTime: 200000
numNodes: 200
enterRate: 500
exitRate: 500
gridHeight: 10000
gridWidth: 10000
chaffGenRate: 200
txGenRate: 1000
circuitWidth: 8
circuitDepth: 8
retryLimit: 7500
buffSize: 50
mixDelay: 50
pktSize: 1024
seed: 256
outfileprefix: "sbd88"
path: "."
genMatrices: false
initialAddressSize: 250
validNodeTransmitReq: 50
addressBookSize: 1000
keepInMemory: false