simTime: 200000
numNodes: 2000
enterRate: 500
exitRate: 2500
gridHeight: 10000
gridWidth: 10000
chaffGenRate: 2000
txGenRate: 5000
circuitWidth: 1
circuitDepth: 8
retryLimit: 7500
buffSize: 50
mixDelay: 50
pktSize: 1024
seed: 256
outfileprefix: "lfg18"
path: "."
genMatrices: false
initialAddressSize: 250
validNodeTransmitReq: 50
addressBookSize: 1000
keepInMemory: false