simTime: 200000
numNodes: 2000
enterRate: 5000
exitRate: 5000
gridHeight: 10000
gridWidth: 10000
chaffGenRate: 200
txGenRate: 1000
circuitWidth: 12
circuitDepth: 4
retryLimit: 7500
buffSize: 50
mixDelay: 50
pktSize: 1024
seed: 256
outfileprefix: "lbsC4"
path: "."
genMatrices: false
initialAddressSize: 250
validNodeTransmitReq: 50
addressBookSize: 1000
keepInMemory: false